name: Run Localization Script Daily
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:  # Permite execução manual
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create dummy README.MD
        run: echo "Temporary README" > README.MD

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dragon-city-utils discord-webhook python-decouple

      - name: Run localization script
      env:
        DISCORD_LOCALIZATION_COMPARISON_WEBHOOK_URL: ${{ secrets.DISCORD_LOCALIZATION_COMPARISON_WEBHOOK_URL }}
        DISCORD_LOCALIZATION_FILE_SENDING_WEBHOOK_URL: ${{ secrets.DISCORD_LOCALIZATION_FILE_SENDING_WEBHOOK_URL }}

        run: |
          python main.py

      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update data from API"
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}